### PR TITLE
DRAGEN has haploid calls?  

### PR DESCRIPTION
**Pull request by bpblanken**

### CODE REVIEW

**Comment by hanars** [comment]
what does it mean at like a biological level for Dragen to have a haploid call? If these calls look substantially different from GATK calls, this feels like something where we need a biologist to weigh in, not for us to just shoehorn the data into our existing schema

**Comment by bpblanken** [comment]
this is direct from hail: https://discuss.hail.is/t/pl-of-haploid-call-induced-error-when-split-multi-hts-in-vcf-produced-by-dragen-pipeline/3116

**Comment by bpblanken** [comment]
(this isn't going into prod, I'm just trying to get the sex/relatedness to work... likely not correctly if the X chromosomes are weird).

**Comment by hanars** [comment]
are we sure this is x chromosome only, and not that we are suddenly being delivered the y chromosome? The discussion you linked to seems to assume all these calls are on the y chromosome

**Comment by bpblanken** [comment]
not just X chromosome.  there's haploid calls on both X/Y.

**Review by hanars — APPROVED** [review]
okay sounds like we need this, but add a comment explaining hwy and maybe add a linkl to the ticket the hail team has to track adding support for this: https://github.com/hail-is/hail/issues/13149

**Pull request closed without merging**
